language: node_js
node_js:
- '7'
cache:
  directories:
    - node_modules
deploy:
- provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  skip_cleanup: true
  on: &2
    branch: master
  bucket: my-portfolio-sud
  region: eu-west-1