language: node_js
node_js:
- '7'
cache:
  directories:
    - node_modules
deploy:
- provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  local_dir: dpl_cd_upload
  skip_cleanup: true
  on: &2
    branch: master
  bucket: my-portfolio-sud
  region: eu-west-1
- provider: codedeploy
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: my-portfolio-sud
  key: latest.zip
  bundle_type: zip
  application: myPortfolio
  deployment_group: myPortfolio
  region: eu-west-1
  on: *2

before_deploy:
  - zip -r latest * >/dev/null
  - mkdir -p dpl_cd_upload
  - mv latest.zip dpl_cd_upload/latest.zip